version: '0'

services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
